### PR TITLE
FAQ and Play improvements

### PR DESCRIPTION
**Pull request by AaronGullickson**
I meant to to do the Play components separately, but it looks like I merged the branches accidentally so I will just go with it. This PR contains new content for the Play page. All of the subsections are filled in except the First Game of MekHQ. 

The PR also contains improvements to the aesthetics of the FAQ to make separate questions more identifiable as well as a few changes to the wording. 

A preview of the website with changes is currently running [here](http://azathoth.uoregon.edu:4000).

### CODE REVIEW

**Comment by AaronGullickson** [comment]
We should probably hold off on approval until I actually add the First Game of MekHQ.

**Comment by AaronGullickson** [comment]
Ok, I think this is ready for review now. I also added a community page as well. I would like this PR to serve as the final PR before we switch over the address from megamek.org, so let me know if anything still doesnt look right.

**Comment by rjhancock** [comment]
A few suggestions:

1. Split the Play page into several pages. Too much content on 1 page especially when dealing with step-by-step information.
2. Left off the servers tab which will update once JS requests are coming from the megamek.org domain.

1 issue found on the light theme with links on the download page.
screen shot 2018-10-08 at 16 43 29

**Comment by AaronGullickson** [comment]
@rjhancock I have split the "First Game of MegaMek" and "First Campaign of MekHQ" into their own pages with sections on the Play page linking to them. I think it makes that page much cleaner. 

The server page is still there at servers.html. it is linked in the Playing Other Humans section of the Play page. I could think about trying to link it more prominently.

**Comment by rjhancock** [comment]
For now I think it's fine on the play page. I think when the new announce API is used on MM, it won't matter as much as MM itself will be able to see what servers are runnings inside of the app.

**Comment by AaronGullickson** [comment]
Fixed the color contrast on the DL page

**Comment by sixlettervariables** [comment]
One nit: the front page should capitalize, 'Dozens'.

**Pull request merged**
